std_id=input('ป้อน ID: ')
student=input('ป้อน name:')
std_birth_year=input('ป้อน birth year: ')
print('------------------------------------')
print(f'ยินดีต้อนรับ'(stu_id)(student) 'to SAU')
print(f'คุณเกิดปี '(stu_birtth_year) แสดงว่าคุณอายุ {2023-int(stu_birth_year)}'ปี')
print('ใช้ ,____________________________')
print('ยินดีต้อนรับ' ,std_id,student, 'to SAU')
print('คุณเกิดปี',stu_birth_year, แสดงว่าคุณอายุ {2023-int,stu_birth_year,}'ปี')
print('ใช้ +____________________________')
print('ยินดีต้อนรับ'+std_id+student+'to SAU')
print('คุณเกิดปี'+std_birth_year+แสดงว่าคุณอายุ {2023-int+std_birth_year+}'ปี')
print('ใช้เมรอด fomat________________________')
print('ยินดีต้อนรับ'() () 'std_id')
print()